language: php
sudo: false
branches:
  only:
    - master
    - develop

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: TYPO3_VERSION=^8.7
    - php: 7.0
      env: TYPO3_VERSION=^8.7
    - php: 7.1
      env: TYPO3_VERSION=^7.6
    - php: 7.0
      env: TYPO3_VERSION=^7.6
    - php: 5.6
      env: TYPO3_VERSION=^7.6

cache:
  directories:
    - $HOME/.composer/cache

addons:
  apt:
    packages:
      - parallel

notifications:
  email:
    - schreiner.tim@gmail.com

before_install:
  - export COMPOSER_ROOT_VERSION=4.6.4
  # Remove xdebug from loaded extensions because of composer
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi

before_script:
  - git clean -dffx
  - composer require typo3/cms="$TYPO3_VERSION"
  - git checkout composer.json

script:
  - >
    echo "Running php lint..."
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;;
  - >
    echo "Running unit and functional tests..."
    .Build/bin/phpunit;

