services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Codemonkey1988\ResponsiveImages\:
    resource: '../Classes/*'

  Codemonkey1988\ResponsiveImages\Rendering\AttributeRenderer:
    public: true

  Codemonkey1988\ResponsiveImages\Variant\VariantFactory:
    public: true

  Codemonkey1988\ResponsiveImages\Service\ConfigurationService:
    public: true

  Codemonkey1988\ResponsiveImages\Service\ImageService:
    shared: true

  Codemonkey1988\ResponsiveImages\EventListener\SkipImageProcessing:
    tags:
      - name: event.listener
        identifier: 'skipImageProcessing'
        event: TYPO3\CMS\Core\Resource\Event\BeforeFileProcessingEvent
