services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Codemonkey1988\ResponsiveImages\:
    resource: '../Classes/*'

  Codemonkey1988\ResponsiveImages\Rendering\AttributeRenderer:
    public: true

  Codemonkey1988\ResponsiveImages\Variant\VariantFactory:
    public: true

  Codemonkey1988\ResponsiveImages\Service\ImageService:
    shared: true
