services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Codemonkey1988\ResponsiveImages\:
    resource: '../Classes/*'

  Codemonkey1988\ResponsiveImages\Variant\PictureImageConfiguration:
    autowire: false

  Codemonkey1988\ResponsiveImages\Rendering\ResponsiveImageRenderer:
    public: true
    shared: true

  Codemonkey1988\ResponsiveImages\Rendering\AttributeRenderer:
    shared: true

  Codemonkey1988\ResponsiveImages\Variant\VariantFactory:
    shared: true

  Codemonkey1988\ResponsiveImages\Service\ConfigurationService:
    shared: true

  Codemonkey1988\ResponsiveImages\Service\ImageService:
    shared: true

  Codemonkey1988\ResponsiveImages\Resource\Service\PictureImageVariant:
    alias: Codemonkey1988\ResponsiveImages\Variant\PictureImageConfiguration
    public: true

  Codemonkey1988\ResponsiveImages\Resource\Service\ImageService:
    alias: Codemonkey1988\ResponsiveImages\Service\ImageService
    public: true

  Codemonkey1988\ResponsiveImages\Resource\Service\PictureVariantsRegistry:
    alias: Codemonkey1988\ResponsiveImages\Variant\PictureImageConfigurationRegistry
    public: true

  Codemonkey1988\ResponsiveImages\EventListener\SkipImageProcessing:
    tags:
      - name: event.listener
        identifier: 'skipImageProcessing'
        event: TYPO3\CMS\Core\Resource\Event\BeforeFileProcessingEvent
