services:
  _defaults:
    autowire: false
    autoconfigure: true
    public: false

  Codemonkey1988\ResponsiveImages\:
    resource: '../Classes/*'

  Codemonkey1988\ResponsiveImages\Resource\Rendering\ResponsiveImageRenderer:
    public: true
    shared: true
    arguments:
      - '@Codemonkey1988\ResponsiveImages\Service\ConfigurationService'
      - '@TYPO3\CMS\Extbase\Service\EnvironmentService'
      - '@Codemonkey1988\ResponsiveImages\Resource\Service\ImageService'

  Codemonkey1988\ResponsiveImages\Resource\Variant\PictureImageVariantFactory:
    public: true
    shared: true
    arguments:
      - '@TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer'
      - '@TYPO3\CMS\Extbase\Configuration\ConfigurationManager'

  Codemonkey1988\ResponsiveImages\Resource\Variant\PictureVariantsRegistry:
    public: true
    shared: true
    arguments:
      - '@Codemonkey1988\ResponsiveImages\Resource\Variant\PictureImageVariantFactory'

  Codemonkey1988\ResponsiveImages\Service\ConfigurationService:
    public: true
    shared: true
    arguments:
      - '@TYPO3\CMS\Extbase\Configuration\ConfigurationManager'

  Codemonkey1988\ResponsiveImages\Resource\Service\ImageService:
    shared: true

  Codemonkey1988\ResponsiveImages\ViewHelpers\ImageViewHelper:
    autowire: true

  Codemonkey1988\ResponsiveImages\EventListener\SkipImageProcessing:
    tags:
      - name: event.listener
        identifier: 'skipImageProcessing'
        event: TYPO3\CMS\Core\Resource\Event\BeforeFileProcessingEvent
